// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJssBS96A4vy7rk_Xaj7cZ_dZ9YoYyLYk',
    appId: '1:1067273287593:web:a8f985cedc460c98f3b6b8',
    messagingSenderId: '1067273287593',
    projectId: 'taskify-flutter-project',
    authDomain: 'taskify-flutter-project.firebaseapp.com',
    storageBucket: 'taskify-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3d18MbzXLX6y0XL1wJhCuRyVN9Gh6pQ',
    appId: '1:1067273287593:android:09014a7b4da1239df3b6b8',
    messagingSenderId: '1067273287593',
    projectId: 'taskify-flutter-project',
    storageBucket: 'taskify-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrmzwEJAwLziceept-REhp8bbSnWOFig4',
    appId: '1:1067273287593:ios:fccd7e2bcce336cbf3b6b8',
    messagingSenderId: '1067273287593',
    projectId: 'taskify-flutter-project',
    storageBucket: 'taskify-flutter-project.appspot.com',
    iosClientId:
        '1067273287593-1deu2q7rgb64l8s2bqu5ahliplbgubtd.apps.googleusercontent.com',
    iosBundleId: 'com.dartapp.taskify',
  );
}
